### ISSUE TITLE
What does the "acute care" specialization mean in plastic surgery?

### ISSUE THREAD

**Issue by EvanArchuletaCO** [sleepy068/ProjectHospital_PlasticSurgery#7]
Hi there! I love the mod; it's fantastic! I was wondering what the acute care hospitalization does specifically in plastic surgery? I tried using that doctor on the hospitalization side of the department and moving them down to the ER trauma center, but it didn't seem to do anything different. Are there specific diagnostic procedures or treatments those doctors can do?

**Comment by sleepy068** [comment]
Hey Mate, it may be used for some treatments, Acute Medicine is generally used in hospitalisation in emergency but some treatments (like Bronchodilators) require it for the treatment to be given. Most likely a complication of some of the surgeries will result in a symptom that needs Acute Medicine for treatment but if you haven't noticed it much, it might be rather rare (some are extremely rare so that's possible).
